#ifndef GLOBALS_H
#define GLOBALS_H

#include <Arduino.h>

#define TEMPL_PIN 0

#define CSAFE_BUZZER_PIN 11
#define CSAFE_POTMETER_PIN A0

#define CRIDDLE_LEDKEY_STROBE_PIN 7
#define CRIDDLE_LEDKEY_CLOCK_PIN 9
#define CRIDDLE_LEDKEY_DIO_PIN 8

#define CSIMON_BUTTON_GREEN_PIN 2
#define CSIMON_BUTTON_RED_PIN 3
#define CSIMON_BUTTON_YELLOW_PIN 4
#define CSIMON_BUTTON_BLUE_PIN 5

#endif
